-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e306ff3b7d0d9a6fc7d128ef9ca2e0b6e6e76e8f
    hooks:
    -   id: flake8
        language_version: python3.5
        args:
        - --ignore=E501,F401,E712
    -   id: check-yaml
        language_version: python3.5
    -   id: end-of-file-fixer
        language_version: python3.5
    -   id: trailing-whitespace
        language_version: python3.5
-   repo: git://github.com/asottile/reorder_python_imports
    sha: 8b583ac1beb0dd0f14c4bceb0a53bb1023cb3dd7
    hooks:
    -   id: reorder-python-imports
        language_version: python3.5
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: ebb1b1bb080b0c960bcf37cf81d09185cec4fc6d
    hooks:
    -   id: pep257
        language_version: python3.5
        args:
        - --ignore=D301
